// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Entry struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID           int64 `json:"id"`
	FromWalletID int64 `json:"from_wallet_id"`
	ToWalletID   int64 `json:"to_wallet_id"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID          int64        `json:"id"`
	FullName    string       `json:"full_name"`
	CpfCnpj     string       `json:"cpf_cnpj"`
	Email       string       `json:"email"`
	Password    string       `json:"password"`
	IsMerchant  sql.NullBool `json:"is_merchant"`
	CreatedAt   sql.NullTime `json:"created_at"`
	LastUpdated sql.NullTime `json:"last_updated"`
}

type Wallet struct {
	ID          int64         `json:"id"`
	UserID      int64         `json:"user_id"`
	Balance     int64         `json:"balance"`
	Currency    string        `json:"currency"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	CountryCode sql.NullInt32 `json:"country_code"`
}
