// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    full_name,
    cpf_cnpj,
    email,
    hashed_password
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING username, full_name, cpf_cnpj, email, hashed_password, password_changed_at, is_merchant, created_at, last_updated
`

type CreateUserParams struct {
	Username       string `json:"username"`
	FullName       string `json:"full_name"`
	CpfCnpj        string `json:"cpf_cnpj"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.CpfCnpj,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.CpfCnpj,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.IsMerchant,
		&i.CreatedAt,
		&i.LastUpdated,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, username)
	return err
}

const getUser = `-- name: GetUser :one
SELECT username, full_name, cpf_cnpj, email, hashed_password, password_changed_at, is_merchant, created_at, last_updated FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.CpfCnpj,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.IsMerchant,
		&i.CreatedAt,
		&i.LastUpdated,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT username, full_name, cpf_cnpj, email, hashed_password, password_changed_at, is_merchant, created_at, last_updated FROM users
ORDER BY username
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Username,
			&i.FullName,
			&i.CpfCnpj,
			&i.Email,
			&i.HashedPassword,
			&i.PasswordChangedAt,
			&i.IsMerchant,
			&i.CreatedAt,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    hashed_password = $2,
    email = $3,
    is_merchant = $4,
    password_changed_at = $5,
    last_updated = now()
WHERE username = $1
RETURNING username, full_name, cpf_cnpj, email, hashed_password, password_changed_at, is_merchant, created_at, last_updated
`

type UpdateUserParams struct {
	Username          string       `json:"username"`
	HashedPassword    string       `json:"hashed_password"`
	Email             string       `json:"email"`
	IsMerchant        sql.NullBool `json:"is_merchant"`
	PasswordChangedAt time.Time    `json:"password_changed_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.HashedPassword,
		arg.Email,
		arg.IsMerchant,
		arg.PasswordChangedAt,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.CpfCnpj,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.IsMerchant,
		&i.CreatedAt,
		&i.LastUpdated,
	)
	return i, err
}
